"""message

Revision ID: 6b1b8bd39861
Revises: 58f80723a54b
Create Date: 2023-09-22 03:01:22.199302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1b8bd39861'
down_revision = '58f80723a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_creator_users'), 'users', ['creator'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_creator_users'), type_='foreignkey')
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
