"""message

Revision ID: 7575ba056aef
Revises: 9de4dc8f36d2
Create Date: 2023-09-22 04:43:45.320035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575ba056aef'
down_revision = '9de4dc8f36d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
