"""message

Revision ID: a926c117de1c
Revises: 76f8af76e9a5
Create Date: 2023-09-19 23:51:53.816689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a926c117de1c'
down_revision = '76f8af76e9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_assignees_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignees_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_users')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contracts_customer_id_customers'), 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_contracts_task_id_tasks'), 'tasks', ['task_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_id', sa.Integer(), nullable=True))
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_tasks_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assignee_id_assignees'), 'assignees', ['assignee_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tasks_contract_id_contracts'), 'contracts', ['contract_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_assignee_id_assignees'), 'assignees', ['assignee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_assignee_id_assignees'), type_='foreignkey')
        batch_op.drop_column('assignee_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_contract_id_contracts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_assignee_id_assignees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_user_id_users'), type_='foreignkey')
        batch_op.alter_column('due_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('contract_id')
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_task_id_tasks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contracts_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('customer_id')

    op.create_table('task_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_task_users_task_id_tasks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_task_users_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assignees')
    # ### end Alembic commands ###
